version: '3.8'
services:
  postgres:
    image: postgis/postgis:15-3.3
    container_name: drone_analytics_db
    environment:
      POSTGRES_DB: drone_analytics
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./data/init-scripts:/docker-entrypoint-initdb.d

volumes:
  postgres_data:
